### ISSUE TITLE
Undetermined gender filter is not working

### ISSUE THREAD

**Issue by kkr-ait** [ejp-rd-vp/vp-portal-issues#22]
**Describe your problem.**

It seems the "Undetermined" gender filter is not working correctly. 

**If it is a bug name steps to reproduce**

Searching for orpha code 730 and choosing "undetermined" as filter gives 1014 results

**Describe the solution you'd like**

I think it should be < 1014 

**Additional context**

Probably related to https://github.com/ejp-rd-vp/vp-portal-issues/issues/21

**Comment by kkr-ait** [comment]
@vabishaa @Ammarbr @HaddadTala

**Comment by Ammarbr** [comment]
thanks @kkr-ait  for bringing up the issue. Honestly, I'm not exactly sure what the right response should be for the gender "undetermined". All I could do was double-check the filters, and they seem to be working fine. @rini21 Can you help us out and let us know what the correct resultCount should be for this request? Appreciate it!

**Comment by rini21** [comment]
@kkr-ait @Ammarbr this is happening because the filter value is unsupported by this resource and is ignored, and a partial request is being performed. My suggestion would be for VP-Portal to make use of the ['warnings' section incoming in the response](https://github.com/ejp-rd-vp/vp-api-specs#-partial-request--response-with-warning-message-example-) to look for 'unsupportedFilters' or 'unsupportedFilterValues' and let the user know that those filter(s)/value(s) will be ignored. 

For now, we have disabled ignoring unsupported filters and the endpoint gives back the correct count '0', and hence will not display ERKReg in the results.
