### ISSUE TITLE
RD Connect / GPAP search results

### ISSUE THREAD

**Issue by kkr-ait** [ejp-rd-vp/vp-portal-issues#25]
When I am searching for neuroblastom (orpha:635) and limit the search 
for italy and patient registries, I get 9 results from RD_Connect-GPAP.
The results are not expandable and there is no link (except when I click 
on the info icon) - However there is no information on what the nature 
of these 9 results is.

**Comment by rini21** [comment]
None of the L2 resources are expandable, including GPAP, ERKNet, Ithaca, Genturis. This is because we have not yet decided what information to give out since the response is only counts and giving out subject information is not ideal. @Ammarbr  @HaddadTala @taspapak please correct me if I'm wrong in assuming that the user would have to contact the resource themselves to gain access to the discovered data.

**Comment by kkr-ait** [comment]
OK - I was just wondering if end-users are going to realize that, or if it would be good to have an explicit message "For more information please contact the resource directly." (+ Link)

**Comment by vabishaa** [comment]
@kkr-ait the "i" Button contains the link to the homepage of the resource. If it is ok we will consider that during the redesign of the resultlist https://github.com/ejp-rd-vp/vp-portal-issues/issues/30 and implement it in the next release
